Clean up crime rate csv

In [57]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Import data

In [58]:
original_df = pd.read_csv(
    "raw_data/NPCMajorOffences2017-2025.csv",
    header=10,
).replace(
    # declared NA values in the dataset
    {
        "na": 0,
        "nec": 0,
        "nes": 0,
        "-": 0,
    }
)
original_df.head(3)

,Data Series,2025,2024,2023,2022,2021,2020,2019,2018,2017
0,Central Police Division - Total,308,263,299,326,230,216,304,347,313
1,Robbery,7,0,3,4,7,3,8,17,14
2,Housebreaking,17,17,13,20,25,29,29,24,18

clip top and bottom descriptive rows

In [59]:
original_df[:-40].tail()

,Data Series,2025,2024,2023,2022,2021,2020,2019,2018,2017
339,Snatch Theft,0,0,0,0,0,0,0,0,0
340,Theft Of Motor Vehicle,0,0,0,0,0,0,0,0,0
341,Outrage Of Modesty,1,0,3,1,1,1,0,0,0
342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
343,Definitions and Footnotes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
offences_df = original_df[:-42].copy()
offences_df.tail(6)

,Data Series,2025,2024,2023,2022,2021,2020,2019,2018,2017
336,Woodlands Police Division - Unknown NPC,1,0,3,1,1,1,0,0,0
337,Robbery,0,0,0,0,0,0,0,0,0
338,Housebreaking,0,0,0,0,0,0,0,0,0
339,Snatch Theft,0,0,0,0,0,0,0,0,0
340,Theft Of Motor Vehicle,0,0,0,0,0,0,0,0,0
341,Outrage Of Modesty,1,0,3,1,1,1,0,0,0

In [61]:
offences_df.isna().sum()

Data Series    0
2025           0
2024           0
2023           0
2022           0
2021           0
2020           0
2019           0
2018           0
2017           0
dtype: int64

Keep rows that have sum for each NPC

In [62]:
npc_df = offences_df.loc[offences_df["Data Series"].str.contains("NPC")]
npc_df

,Data Series,2025,2024,2023,2022,2021,2020,2019,2018,2017
6,Central Police Division - Bukit Merah East NPC,78,53,66,76,65,60,73,97,89
12,Central Police Division - Marina Bay NPC,146,137,158,152,90,77,147,156,134
18,Central Police Division - Rochor NPC,84,70,73,96,72,76,84,94,89
24,Central Police Division - Unknown NPC,0,3,2,2,3,3,0,0,0
36,Clementi Police Division - Bukit Merah West NPC,52,55,33,43,41,54,52,52,64
42,Clementi Police Division - Clementi NPC,34,32,31,31,32,43,48,40,50
48,Clementi Police Division - Jurong East NPC,51,50,45,52,45,46,62,56,64
54,Clementi Police Division - Queenstown NPC,42,70,43,43,71,60,69,65,66
60,Clementi Police Division - Unknown NPC,0,0,1,0,1,0,0,0,0
72,Tanglin Police Division - Bishan NPC,28,26,29,25,37,19,22,44,29
78,Tanglin Police Division - Bukit Timah NPC,21,23,31,31,33,29,39,41,25
84,Tanglin Police Division - Kampong Java NPC,35,33,36,31,45,39,35,33,38
90,Tanglin Police Division - Orchard NPC,140,134,129,137,66,62,156,185,158
96,Tanglin Police Division - Toa Payoh NPC,44,34,53,50,49,53,69,50,51
102,Tanglin Police Division - Unknown NPC,2,1,2,3,1,0,0,0,0
114,Ang Mo Kio Police Division - Ang Mo Kio North NPC,33,18,28,34,35,35,26,34,34
120,Ang Mo Kio Police Division - Ang Mo Kio South NPC,29,15,34,26,30,13,40,44,35
126,Ang Mo Kio Police Division - Hougang NPC,42,25,48,68,57,51,71,67,55
132,Ang Mo Kio Police Division - Punggol NPC,61,56,39,51,44,43,53,33,30
138,Ang Mo Kio Police Division - Sembawang NPC,0,0,0,0,0,0,0,32,36
144,Ang Mo Kio Police Division - Sengkang NPC,84,67,62,68,83,56,67,61,72
150,Ang Mo Kio Police Division - Serangoon NPC,39,32,33,56,38,25,27,49,29
156,Ang Mo Kio Police Division - Yishun North NPC,0,0,0,0,0,0,0,64,61
162,Ang Mo Kio Police Division - Yishun South NPC,0,0,0,0,0,0,0,38,32
168,Ang Mo Kio Police Division - Woodleigh NPC,39,40,13,0,0,0,0,0,0
174,Ang Mo Kio Police Division - Unknown NPC,11,4,4,1,1,2,0,0,0
186,Bedok Police Division - Bedok NPC,52,55,78,91,80,64,86,88,86
192,Bedok Police Division - Changi NPC,32,33,36,47,32,14,22,52,31
198,Bedok Police Division - Geylang NPC,67,75,79,90,73,76,89,106,104
204,Bedok Police Division - Marine Parade NPC,26,35,36,39,32,36,36,39,35
210,Bedok Police Division - Pasir Ris NPC,19,24,36,39,33,27,32,36,23
216,Bedok Police Division - Tampines NPC,50,34,54,61,56,42,56,55,58
222,Bedok Police Division - Unknown NPC,6,7,5,3,0,1,0,0,0
234,Jurong Police Division - Bukit Batok NPC,45,60,61,42,52,46,52,62,50
240,Jurong Police Division - Bukit Panjang NPC,27,36,34,28,32,36,30,46,30
246,Jurong Police Division - Choa Chu Kang NPC,42,54,53,50,61,63,71,56,47
252,Jurong Police Division - Jurong West NPC,42,56,57,57,63,46,51,62,59
258,Jurong Police Division - Nanyang NPC,55,55,61,66,54,57,59,79,64
264,Jurong Police Division - Woodlands NPC,0,0,0,0,0,0,0,0,0
270,Jurong Police Division - Woodlands East NPC,0,0,0,0,0,0,0,51,60
276,Jurong Police Division - Woodlands West NPC,0,0,0,0,0,0,0,59,70
282,Jurong Police Division - Unknown NPC,2,3,4,0,2,2,0,0,0
294,Woodlands Police Division - Woodlands East NPC,35,39,36,35,45,47,56,2,0
300,Woodlands Police Division - Woodlands West NPC,50,34,40,35,38,43,53,7,0
306,Woodlands Police Division - Yishun North NPC,0,32,37,43,42,59,64,6,0
312,Woodlands Police Division - Yishun South NPC,0,16,10,18,26,26,18,1,0
318,Woodlands Police Division - Yishun NPC,60,3,0,0,0,0,0,0,0
324,Woodlands Police Division - Sembawang NPC,34,19,33,38,35,46,27,2,0
336,Woodlands Police Division - Unknown NPC,1,0,3,1,1,1,0,0,0

In [63]:
npc_df.to_csv("cleaned_data/OffencesByNPC2017-2025.csv")

In [64]:
test_df = npc_df.set_index(npc_df["Data Series"], drop=True)
test_df.head()

,Data Series,2025,2024,2023,2022,2021,2020,2019,2018,2017
Data Series,,,,,,,,,,
Central Police Division - Bukit Merah East NPC,Central Police Division - Bukit Merah East NPC,78,53,66,76,65,60,73,97,89
Central Police Division - Marina Bay NPC,Central Police Division - Marina Bay NPC,146,137,158,152,90,77,147,156,134
Central Police Division - Rochor NPC,Central Police Division - Rochor NPC,84,70,73,96,72,76,84,94,89
Central Police Division - Unknown NPC,Central Police Division - Unknown NPC,0,3,2,2,3,3,0,0,0
Clementi Police Division - Bukit Merah West NPC,Clementi Police Division - Bukit Merah West NPC,52,55,33,43,41,54,52,52,64

In [53]:
sns.lineplot(
    x=npc_df.columns[1:],
    y=npc_df.loc["Data Series"]
)

KeyError: 'Data Series'